export { default as Title } from './1-Title.astro';
export { default as Impact } from './2-Impact.astro';
export { default as Architecture } from './3-Architecture.astro';
export { default as FigmaComponents } from './4-FigmaComponents.astro';
export { default as Release } from './5-Release.astro';
export { default as Adoption } from './6-Adoption.astro';
export { default as Accessibility } from './7-Accessibility.astro';
export { default as GridAndLayout } from './8-GridAndLayout.astro';
export { default as ThankYou } from './9-ThankYou.astro';
